//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.31 at 12:55:29 PM CEST 
//


package minecraft.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for UnnamedGridDefinition complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="UnnamedGridDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="min">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="z" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="max">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="z" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnnamedGridDefinition", propOrder = {
        "min",
        "max"
})
public class UnnamedGridDefinition {

    @XmlElement(required = true)
    protected Min min;
    @XmlElement(required = true)
    protected Max max;

    /**
     * Gets the value of the min property.
     *
     * @return possible object is
     * {@link Min }
     */
    public Min getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     *
     * @param value allowed object is
     *              {@link Min }
     */
    public void setMin(Min value) {
        this.min = value;
    }

    /**
     * Gets the value of the max property.
     *
     * @return possible object is
     * {@link Max }
     */
    public Max getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     *
     * @param value allowed object is
     *              {@link Max }
     */
    public void setMax(Max value) {
        this.max = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="z" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Max {

        @XmlAttribute(name = "x", required = true)
        protected int x;
        @XmlAttribute(name = "y", required = true)
        protected int y;
        @XmlAttribute(name = "z", required = true)
        protected int z;

        /**
         * Gets the value of the x property.
         */
        public int getX() {
            return x;
        }

        /**
         * Sets the value of the x property.
         */
        public void setX(int value) {
            this.x = value;
        }

        /**
         * Gets the value of the y property.
         */
        public int getY() {
            return y;
        }

        /**
         * Sets the value of the y property.
         */
        public void setY(int value) {
            this.y = value;
        }

        /**
         * Gets the value of the z property.
         */
        public int getZ() {
            return z;
        }

        /**
         * Sets the value of the z property.
         */
        public void setZ(int value) {
            this.z = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="z" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Min {

        @XmlAttribute(name = "x", required = true)
        protected int x;
        @XmlAttribute(name = "y", required = true)
        protected int y;
        @XmlAttribute(name = "z", required = true)
        protected int z;

        /**
         * Gets the value of the x property.
         */
        public int getX() {
            return x;
        }

        /**
         * Sets the value of the x property.
         */
        public void setX(int value) {
            this.x = value;
        }

        /**
         * Gets the value of the y property.
         */
        public int getY() {
            return y;
        }

        /**
         * Sets the value of the y property.
         */
        public void setY(int value) {
            this.y = value;
        }

        /**
         * Gets the value of the z property.
         */
        public int getZ() {
            return z;
        }

        /**
         * Sets the value of the z property.
         */
        public void setZ(int value) {
            this.z = value;
        }

    }

}
